### ISSUE TITLE
キャッシュの取得に失敗する

### ISSUE THREAD

**Issue by Lishrk** [kairi003/NarouReaderMod#4]
お世話になっております。
ver0.2.2 でキャッシュの取得に失敗します。
試しに新規で作品をインポートしたところ、目次も表示されませんでした。

**Comment by kairi003** [comment]
本当ですね
調査してみますが大きく仕様が変わっていたら対応できないので期待せずにお待ち下さい…

**Comment by kairi003** [comment]
原因の一つ判明しました
cssクラス名が変わってますね…
対応できるか頑張ってみます

**Comment by kairi003** [comment]
新HTML対応バージョン v0.2.3 をリリースしました

**Comment by Lishrk** [comment]
ありがとうございます！

**Comment by kairi003** [comment]
すみませんバグがあったので次のリリースをお待ち下さい

**Comment by kairi003** [comment]
多分これで大丈夫なはずです…
